added files for Collectd 5.6 support
AerisCloud/ansible-collectd pull request #10
Opened 2016-10-11 09:38 UTC by tokyowizard

CentOS 7 has updated the default version of collectd from 5.5 to 5.6.

This PR provides the `collectd.conf` and `librato.conf` for collectd v5.6.

The `collectd.conf` is taken from the default install of CentOS 7 with the same settings from the 5.5 file.

2016-10-11 15:06 UTC, MiLk requested changes
Please stop adding a file for each version.
Instead, use jinja to change what need to be changed inside the template file according to the version.

For the main config file, you can remove everything concerning plugins. What is not commented about plugins should be moved to a different file to be re used across versions.

And disable `AutoLoadPlugin`.

2016-10-14 12:44 UTC, tokyowizard commented
There is now just 1 collectd.conf.j2 template file with jinja that include the changes according to the version.

All the plugins have been moved to their own files.

And `AutoLoadPlugin` is disabled.

2016-10-15 00:51 UTC, MiLk requested changes

2016-10-15 00:51 UTC, MiLk commented on tasks/main.yml
> +    src=plugin-configs/librato.conf.j2
Can you not add librato to the plugin list to use only one block?

2016-10-15 00:51 UTC, MiLk commented on tasks/main.yml
> +  when: monitor_coretemp|bool
Use the conditional inside the file. It's ok to upload an empty file.

2016-10-15 00:51 UTC, MiLk commented on tasks/main.yml
> +  when: use_graphite|bool and collectd_forwarder is defined and collectd_forwarder == inventory_hostname
Same as coretemp.

2016-10-15 00:51 UTC, MiLk commented on templates/collectd.conf.j2
> +#AutoLoadPlugin false
Remove the comment. Set it explicitly to false.

2016-10-15 00:51 UTC, MiLk commented on templates/collectd.conf.j2
> +#<Plugin syslog>
You probably need to leave the configuration for syslog plugin.
You should move it just after the `LoadPlugin syslog` line.

2016-10-15 00:51 UTC, MiLk commented on templates/collectd.conf.j2
>  ##############################################################################
Remove everything from here to`Include "/etc/collectd.d"`.
It should be only comments.

2016-10-15 00:51 UTC, MiLk commented on templates/plugin-configs/plugin.conf.j2
> +LoadPlugin vmem
That file doesn't seem to be used.

2016-10-17 10:26 UTC, tokyowizard commented on templates/collectd.conf.j2
>  ##############################################################################
I've removed all uncommented `LoadPlugin` and into its own .conf file, which were the defaults (`syslog`,`cpu`,`interface`,`load`,`memory`).
The rest are only comments.

2016-10-17 11:07 UTC, MiLk requested changes
Don't squash your PR, I feel like I have to review the 1895 lines you changed every time.

2016-10-17 11:07 UTC, MiLk commented on README.md
> +The `collectd_load_plugins` variable defines the plugins to be loaded. Default plugins are below:
The name should be `collectd_plugins`.

2016-10-17 11:07 UTC, MiLk commented on README.md
> +LoadPlugin syslog
Why not use a list with just the plugin names?

2016-10-17 11:07 UTC, MiLk commented on templates/plugin-configs/python.conf.j2
> +LoadPlugin python
Why is it outside of the condition?

2016-10-17 11:07 UTC, MiLk commented on templates/plugin-configs/python.conf.j2
> +<LoadPlugin write_graphite>
It seems to be a duplicate of `templates/plugin-configs/write_graphite.conf.j2`

2016-10-17 11:07 UTC, MiLk commented on templates/collectd.conf.j2
>  ##############################################################################
Please remove all the commented configuration from that point.
It's unwanted noise and make it harder to maintain.

2016-10-18 04:18 UTC, tokyowizard commented
Thank you for the comments. I've made the fixes. When you think it's good, shall I squash it before the PR is merged?

2016-10-18 05:11 UTC, MiLk approved these changes

2016-10-18 05:11 UTC, merged