have all machines send to Librato when a collectd_forwarder is not defined
AerisCloud/ansible-collectd pull request #11
Opened 2017-05-19 15:03 UTC by tokyowizard

Sometimes a collectd server does not exist, so all machines would need to their metrics sent to Librato.

When using [Librato](https://www.librato.com), this PR allows all machines to be configured to send to Librato when `collectd_forwarder` is not defined.

2017-05-20 04:39 UTC, MiLk commented on templates/plugin-configs/librato.conf.j2
> +{% if (collectd_forwarder is defined and collectd_forwarder == inventory_hostname) or (collectd_forwarder is not defined) %}
What about setting a default value for `collectd_forwarder` to empty string? this would allow to remove the `is defined` check.

2017-05-22 10:49 UTC, tokyowizard commented on templates/plugin-configs/librato.conf.j2
> +{% if (collectd_forwarder is defined and collectd_forwarder == inventory_hostname) or (collectd_forwarder is not defined) %}
Ah ok. Will do.

2017-05-22 12:55 UTC, MiLk requested changes

2017-05-22 12:55 UTC, MiLk commented on templates/plugin-configs/network.conf.j2
> +    {% if collectd_forward_to_logstash|bool == true %}
you don't need the `== true`

2017-05-24 03:29 UTC, tokyowizard commented on templates/plugin-configs/network.conf.j2
> +    {% if collectd_forward_to_logstash|bool == true %}
ok, I'll remove it.

2017-05-24 03:34 UTC, MiLk approved these changes

2017-05-24 06:14 UTC, MiLk approved these changes

2017-05-24 06:14 UTC, merged